version: "3.2"
services:
  database:
    container_name: apartment-container
    image: mysql:8.0.22
    volumes:
      - ~/docker/mysql/apartment/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/apartment/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/apartment/var/log/mysql:/var/log/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - MYSQL_DATABASE=apartmentdb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    ports:
      - "3306:3306"
    networks:
      - test_env
  application:
    container_name: apartment-application-container
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://apartment-container:3306/apartmentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - test_env



networks:
  test_env:
    driver: bridge